#cloud-config

# Update and upgrade packages
apt:
  primary:
    - arches: [default]
      uri: http://us.archive.ubuntu.com/ubuntu/

package_update: true
package_upgrade: true

# Install prerequisites packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3
  - docker.io

runcmd:
  # URL-encode the password
  - DB_PASS=$(echo "${db_pass}" | python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read().strip(), safe=""))')

  # Write DSN environment variable and other configs
  - mkdir -p /opt/app
  - echo "DSN=postgres://${db_user}:$DB_PASS@${db_host}:${db_port}/${db_name}" > /opt/app/envfile

  # Pull and run the Docker image from Scaleway registry
  - docker pull ${registry_endpoint}/app:latest
  - docker rm -f tasktracker || true
  - docker run -d --name tasktracker -p ${lb_port}:${lb_port} --env-file /opt/app/envfile ${registry_endpoint}/app:latest
